package db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * This implementation of the DBConnector interface is for MySQL databases.
 * @author iquigley
 */
public class MySQLConnector implements DBConnector{

    Connection connection = null;
    Statement statement = null;

    // For standard MySQL Ports.
    static String host = "jdbc:mysql://localhost:3306/zombie_game";
    // For mac users of MAMP using the default MySQL port
    // static String host = "jdbc:mysql://localhost:8889/zombie_game";
    static String user = "root";
    static String password = "root";

    public MySQLConnector() {
        // Initialize the connection at start-up.
        this.connect();
    }


    /**
     * Generates a MySQL specific string for saving objects to the database.
     * @param _keyValuePairs
     * @param _table
     * @return int
     */
    @Override
    public int createObject(Map<String, String> _keyValuePairs, String _table) {
        String query =  "INSERT INTO " + _table;
        String names = "(";
        String values = "VALUES (";
        for (Map.Entry<String, String> entry : _keyValuePairs.entrySet()){
            names+=  " `" + entry.getKey() + "`, ";
            values+= " '" + entry.getValue() + "', ";
        }
        // Trim off the last comma.
        names = names.substring(0, names.length() - 2);
        values = values.substring(0, values.length() - 2);
        names+= ") ";
        values+= ")";
        query+= names + values;
        // Execute the query.
        int newKey = this.executeInsert(query);
        if (newKey == -1) {
            System.out.println("Database Error: Could not create new record");
            return 0;
        }
        return newKey;
    }


    /**
     * This helper function runs the query given by the above method.
     * @TODO - See if we can consolidate this method with the other helper methods
     * below.
     * @param query
     * @return
     */
    private int executeInsert(String query){
        int key = -1;
        try {
            this.statement.executeUpdate(query, Statement.RETURN_GENERATED_KEYS);
            ResultSet result = statement.getGeneratedKeys();
            if (result.next()){
                key = result.getInt(1);
            }
        } catch (SQLException ex) {
            System.out.println("Query Error: " + ex.getMessage());
            Logger.getLogger(DataStore.class.getName()).log(Level.SEVERE, null, ex);
        }
        return key;
    }


    /**
     * Generates a MySQL query for updating an object to the database.
     * @param _keyValuePairs
     * @param _uuid
     * @param _table
     * @return Boolean
     */
    @Override
    public Boolean updateObject(Map<String,String> _keyValuePairs, String _uuid, String _table) {
        String query =  "UPDATE " + _table + " SET ";
        //iterate over map
        String updates = "";
        for (Map.Entry<String, String> entry : _keyValuePairs.entrySet()){
            updates+= " `" + entry.getKey() + "` = \"" + entry.getValue() + "\",";
        }
        //shed off the last comma
        updates = updates.substring(0, updates.length()-1);
        query = query + updates + " WHERE `uuid` = " + _uuid;

        this.executeUpdate(query);
        return true;
    }


    /**
     * This helper method runs the query generated by the updateObject methed.
     * @param query
     */
    private void executeUpdate(String query){
        try {
            statement.executeUpdate(query, Statement.NO_GENERATED_KEYS);
        } catch (SQLException ex) {
            System.out.println("Query Error: " + ex.getMessage());
            Logger.getLogger(DataStore.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * Reads an object from the database given a set of conditionals in name-value
     * pair format.
     * @TODO - Implement this method.
     * @param _keyValuePairs
     * @return
     */
    @Override
    public Map<String,String> readObject(Map<String,String> _keyValuePairs) {
        return null;
    }

    /**
     * This helper method executes the read operation.
     * @TODO - Implement this method.
     * @param query
     * @return ResultSet
     */
    private ResultSet executeRead(String query) {
        ResultSet results = this.runQuery(query);
        try {
            // check to see if there are any results
            if (results.next()){
                // do nothing, we just now know that we have data
            }
            return results;
        }catch(SQLException ex) {
            System.out.println("Database Error: No Result Found." + ex.getMessage());
        }
        return null;
    }


    /**
     * This method deletes an object from the database.
     * @TODO - Implement this method. We want to just make an update to the database
     * to set an active flag to false instead of actually deleting records.
     * @param uuid
     * @return Boolean
     */
    @Override
    public Boolean deleteObject(String uuid) {
        throw new UnsupportedOperationException("Not supported yet.");
    }


    /**
     * Generic helper method for running queries.
     * @param query
     * @return ResultSet
     */
    protected ResultSet runQuery(String query){
        ResultSet result = null;
        try {
            result = statement.executeQuery(query);
        } catch (SQLException ex) {
            System.out.println("Query Error: " + ex.getMessage());
        }
        return result;
    }

    /**
     * This helper method establishes a connection to the database.
     */
    private void connect() {
        try {
            this.connection = DriverManager.getConnection(MySQLConnector.host, MySQLConnector.user, MySQLConnector.password);
            this.statement = connection.createStatement();
        } catch (SQLException ex) {
            System.out.println("No Connection to DB: " + ex.getMessage());
        }
    }


    /**
     * This helper method closes the connection to the database once the queries are
     * finished.
     */
    private void closeConnection(){
       if (statement != null) {
            try {
              statement.close();
            } catch (SQLException ex) {
                System.out.println("Statement Close Error: " + ex.getMessage());
                Logger.getLogger(DataStore.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       if (this.connection != null) {
            try {
                connection.close();
            } catch (SQLException ex) {
                System.out.println("Connection Close Error: " + ex.getMessage());
                Logger.getLogger(DataStore.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

}
